######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 30 22:37:56 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
